- hosts: common
  become: yes
  become_method: sudo
  become_user: root
  tasks:
    - name: Run a shell command
      shell: ls -l 
    - name: pause playbook
      pause:
        minutes: 5
    - name: Run a shell command
      shell: ls -l /home/vivek

